### ISSUE TITLE
Picker is cut when component is in overflow:hidden container

### ISSUE THREAD

**Issue by menelai** [Agranom/ngx-material-timepicker#130]
Can you make the popup appended to body?

**Comment by Agranom** [comment]
What do you mean ?

**Comment by menelai** [comment]
```
div(style="width:300px; height:100px; overflow:hidden;")
  input.timeinput(type="time", matInput,  [formControl]="timeControl", #timeinput, [ngxTimepicker]="picker", [format]="24")
```
Timepicker popup will be cut with the container div.

**Comment by Agranom** [comment]
Try to move <ngx-material-timepicker> out from div

**Comment by menelai** [comment]
Нет, капитан.

**Comment by nikiforenkoanton** [comment]
Also has an issues with `opacity` and `transform` on parent component.

**Comment by Agranom** [comment]
I'll add possibility to bind timepicker to an input. Without overlay

**Comment by nikiforenkoanton** [comment]
In the case of binding timepicker to the input can be issues when the parent container has a lower width or height, so it will cut off timepicker, But as additional feature it's fine.
Adding time-picker to the body, like Material CDK does with it's overlays, probably will be more reliable solution.

This component also behaves in that way:
https://github.com/owsolutions/amazing-time-picker

**Comment by Agranom** [comment]
Done. Now component appends to body as a child element

**Comment by nikiforenkoanton** [comment]
Still doesn't work. :(
Opens in the same place and adds empty <ngx-material-timepicker> to the body.

**Comment by Agranom** [comment]
@nikiforenkoanton provide with an example on https://stackblitz.com pls, because I cannot reproduce it

**Comment by Agranom** [comment]
Already reproduced the bug. Will fix it soon

**Comment by nikiforenkoanton** [comment]
Thank you a lot. There was a problems with reproducing it on stackblitz due to dependencies issues (something wrong with luxon).

**Comment by Agranom** [comment]
Fixed (I hope). Update to v.5.1.1

**Comment by nikiforenkoanton** [comment]
Works as expected, great job!
