### ISSUE TITLE
Issue in version 5

### ISSUE THREAD

**Issue by dawa-liverpudlian** [Agranom/ngx-material-timepicker#215]
Cannot read property 'split' of null in ngx material timepicker

**Comment by Agranom** [comment]
need more details

**Comment by dawa-liverpudlian** [comment]
just updated the version and got this error in console. Changed the version to 4.0.2 and got it working again.

**Comment by Agranom** [comment]
what timepicker version do you use ?

**Comment by dawa-liverpudlian** [comment]
used the latest one when i got the error.

**Comment by Agranom** [comment]
can you provide me with example on https://stackblitz.com please ?

**Comment by RobinDeBaets** [comment]
This is happening to me using this (notice the `ngModel`): 
```
<mat-form-field *ngIf="test != null">
  <input matInput name="start_time" placeholder="24hr format" aria-label="24hr format" [ngxTimepicker]="fullTime" [format]="24" [(ngModel)]="test" readonly>
  <ngx-material-timepicker #fullTime></ngx-material-timepicker>
</mat-form-field>
```

And setting `test` to `''` or `null`

**Comment by mtinnes** [comment]
I'm getting the same error when binding with ngModel:

```
ScheduleEditComponent.html:128 ERROR TypeError: Cannot read property 'split' of null
    at Function.push../node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js.TimeAdapter.parseTime (ngx-material-timepicker.js:74)
    at Function.push../node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js.TimeAdapter.formatTime (ngx-material-timepicker.js:80)
    at TimepickerDirective.set [as defaultTime] (ngx-material-timepicker.js:680)
    at TimepickerDirective.push../node_modules/ngx-material-timepicker/fesm5/ngx-material-timepicker.js.TimepickerDirective.writeValue (ngx-material-timepicker.js:703)
    at setUpControl (forms.js:2206)
    at NgModel.push../node_modules/@angular/forms/fesm5/forms.js.NgModel._setUpStandalone (forms.js:4955)
    at NgModel.push../node_modules/@angular/forms/fesm5/forms.js.NgModel._setUpControl (forms.js:4942)
    at NgModel.push../node_modules/@angular/forms/fesm5/forms.js.NgModel.ngOnChanges (forms.js:4872)
    at checkAndUpdateDirectiveInline (core.js:21092)
    at checkAndUpdateNodeInline (core.js:29494)
```

appears to error out during the initialization, before any value is bound

**Comment by mtinnes** [comment]
Also not getting the model change event via (ngModelChange). Selecting a new time via the picker updates the input field, but the event is never fired. Angular looks like the following:

```
<mat-form-field appearance="legacy">
                                <mat-icon matPrefix (click)="startTimePicker.open()">access_time</mat-icon>
                                <input matInput readonly
                                       [ngxTimepicker]="startTimePicker"
                                       [ngModel]="startTime | scheduleTime"
                                       (ngModelChange)="startTime=parseTime($event)"
                                       [ngModelOptions]="{standalone: true}"
                                       [disabled]="!canEdit">
                                <button mat-button *ngIf="startTime" matSuffix mat-icon-button aria-label="Clear" (click)="startTime=null">
                                    <mat-icon>close</mat-icon>
                                </button>
                            </mat-form-field>
<ngx-material-timepicker #startTimePicker></ngx-material-timepicker>
```

**Comment by Agranom** [comment]
I’ll fix it in the next release

**Comment by Agranom** [comment]
Fixed in v5.2.0

**Comment by TdoubleG** [comment]
this seems to be still present in v5.2.1

I get the error, despite I habe a time

```
<ngx-timepicker-field formControlName="from"
                                [format]="24"
                                [defaultTime]="openings.from">
          </ngx-timepicker-field>
```

this is what openings looks like
```
closed: false
day: "Monday"
from: "12:00"
to: "22:00"
```
