### ISSUE TITLE
[question] prevent Invalid DateTime

### ISSUE THREAD

**Issue by Dexerius** [Agranom/ngx-material-timepicker#266]
Hello,

I'd like to prevent user from entering invalid time into input field within timepicker. I have set: enableKeyboardInput="true" so when I toggle timepicker I can type into the fields above clock. They are restricted to only accept numbers, but I can input more than two digits or a value out of valid interval and then the field value changes to 'Invalid DateTime' which I have to remove to start setting time again. So I'd like to prevent user from entering invalid value or if they do, change the field value back to time the  clock's showing. Is there a way to accomplish this?
Thanks for any suggestions.

**Comment by darioespositoW3** [comment]
Hi!, 
I have a same issue. 
Does anyone know how to fix this?

Thanks for advance.

**Comment by Dexerius** [comment]
This is what I'm doing now:
`var dialInputs = document.getElementsByClassName('timepicker-dial__control');
if((<HTMLInputElement>dialInputs[0]).value.includes("Invalid DateTime")) 
     (<HTMLInputElement>dialInputs[0]).value = "";`
Setting value to empty string "" if there is "Invalid DateTime". I'd like to set it to value the clock is pointing to.

**Comment by Agranom** [comment]
Hi. How did you manage to input more than 2 numbers ? Can you reproduce it on the demo page https://agranom.github.io/ngx-material-timepicker/ ?

**Comment by Dexerius** [comment]
> 
> 
> Hi. How did you manage to input more than 2 numbers ? Can you reproduce it on the demo page https://agranom.github.io/ngx-material-timepicker/ ?

Hello.
On your demo page in the "Editable dial" example, when you expand timepicker, you can type unlimited number of digits into the input fields above the clock.

**Comment by Agranom** [comment]
Are you typing into input field or into clock dial ?

**Comment by Dexerius** [comment]
Those two input fields above clock.

**Comment by Agranom** [comment]
It's strange, because I cannot type invalid time. Could you make a screenshot pls?

**Comment by Dexerius** [comment]
![timePicker](https://user-images.githubusercontent.com/26347583/70623856-4a0ab100-1c1f-11ea-8fce-200c5b909932.png)

**Comment by Agranom** [comment]
What the browser do you use?

**Comment by Dexerius** [comment]
Firefox, but I tried in explorer and edge and same behavior.

**Comment by Agranom** [comment]
Have you tried in chrome?

**Comment by Dexerius** [comment]
nope, shall I try?

**Comment by Dexerius** [comment]
Ok, I tried in chrome its same in all browsers

**Comment by Agranom** [comment]
It's weird, cause I cannot reproduce it

**Comment by Dexerius** [comment]
Just tried it on phone, and there it works. Can't input three digits or invalid time.

**Comment by Agranom** [comment]
I really don't know why it doesn't work for you on your PC

**Comment by kofizzz** [comment]
Hi,

I can confirm that the issue reported is correct. If you enable free text typing into the field and click somewhere else on the page to remove the focus the error message will appear overriding the freehand text.

Might be nicer to allow custom validators to be set.

Thanks

**Comment by Totati** [comment]
Hi, I can reproduce it in Windows 10, Chrome 79, Chromium Edge 79 too.

**Comment by Agranom** [comment]
The issue is resolved. Update to the latest version (v.5.4.0).

**Comment by mynameisx666** [comment]
I installed 5.4.1 but this still exists
![image](https://user-images.githubusercontent.com/62140714/76620065-4f9dcd00-6567-11ea-8dd3-d1b69559c9f8.png)
