### ISSUE TITLE
Time picker accepts only one digit from Keyboard number pad.

### ISSUE THREAD

**Issue by Jithesh-Menon** [Agranom/ngx-material-timepicker#289]
Time picker allows entering 2 characters/numbers from main numbers on the keyboard (those on top of the keyboard) but when using the keys on the number pad (at the right-hand end of the keyboard) user can only enter one character.

**Comment by epstarr** [comment]
I am able to duplicate this on my site as well as the demo site.

**Comment by Jithesh-Menon** [comment]
> I am able to duplicate this on my site as well as the demo site.

Hi @epstarr ,

I would like to share and confirm one more issue with you ([https://github.com/Agranom/ngx-material-timepicker/issues/264] - RESET Time picker).
Thank you.

**Comment by Agranom** [comment]
I'll check this issue

**Comment by Agranom** [comment]
The issue is resolved. Update to the latest version (v.5.4.0).

**Comment by Jithesh-Menon** [comment]
Hi @Agranom ,
I have updated the version to 5.4.3, I am still facing this issue..

**Comment by Jithesh-Menon** [comment]
@epstarr ,
Are you able to replicate this issue in your application even after upgrading to 5.4.0?

**Comment by Jithesh-Menon** [comment]
@Agranom ,
This has an impact on the locale as well. When I used proper locale information, this issue also got fixed.
Thank you so much. :)
